DROP SEQUENCE USER_SEQ;
CREATE SEQUENCE USER_SEQ ORDER;

DROP TABLE USER_T;
CREATE TABLE USER_T (
    USER_NO   NUMBER            NOT NULL
  , USER_ID   VARCHAR2(30 BYTE) NOT NULL UNIQUE
  , USER_NAME VARCHAR2(30 BYTE)
  , JOINED_AT DATE
  , CONSTRAINT PK_USER PRIMARY KEY(USER_NO)
);


SELECT * FROM USER_T;
